# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
package:
  name: librmm
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - CCACHE_DIR
    - CCACHE_NOHASHDIR
    - CCACHE_COMPILERCHECK
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
  run_exports:
    - {{ pin_subpackage("librmm", max_pin="x.x") }}

requirements:
  build:
    - cmake >=3.20.1
  host:
    - cudatoolkit {{ cuda_version }}.*
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - spdlog>=1.8.5,<1.9

test:
  commands:
    - test -f $PREFIX/include/rmm/thrust_rmm_allocator.h
    - test -f $PREFIX/include/rmm/logger.hpp
    - test -f $PREFIX/include/rmm/cuda_stream.hpp
    - test -f $PREFIX/include/rmm/cuda_stream_view.hpp
    - test -f $PREFIX/include/rmm/cuda_stream_pool.hpp
    - test -f $PREFIX/include/rmm/device_uvector.hpp
    - test -f $PREFIX/include/rmm/device_scalar.hpp
    - test -f $PREFIX/include/rmm/device_buffer.hpp
    - test -f $PREFIX/include/rmm/detail/aligned.hpp
    - test -f $PREFIX/include/rmm/detail/error.hpp
    - test -f $PREFIX/include/rmm/detail/exec_check_disable.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/arena.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/free_list.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/coalescing_free_list.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/fixed_size_free_list.hpp
    - test -f $PREFIX/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/arena_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/binning_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/cuda_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/device_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/fixed_size_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/limiting_resource_adaptor.hpp
    - test -f $PREFIX/include/rmm/mr/device/logging_resource_adaptor.hpp
    - test -f $PREFIX/include/rmm/mr/device/managed_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/owning_wrapper.hpp
    - test -f $PREFIX/include/rmm/mr/device/per_device_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/pool_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/device/thread_safe_resource_adaptor.hpp
    - test -f $PREFIX/include/rmm/mr/device/thrust_allocator_adaptor.hpp
    - test -f $PREFIX/include/rmm/mr/host/host_memory_resource.hpp
    - test -f $PREFIX/include/rmm/mr/host/new_delete_resource.hpp
    - test -f $PREFIX/include/rmm/mr/host/pinned_memory_resource.hpp

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: librmm library
