# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
# Copyright (c) 2018-2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}
  date_string: ${{ env.get("RAPIDS_DATE_STRING") }}
  head_rev: ${{ git.head_rev( "." )[:8] }}

recipe:
  name: librmm-split

cache:
  source:
    path: ../../..

  requirements:
    build:
      - cmake ${{ cmake_version }}
      - ninja
      - ${{ compiler("c") }}
      - ${{ compiler("cxx") }}
      - ${{ compiler("cuda") }}
      - cuda-version =${{ cuda_version }}
      - ${{ stdlib("c") }}

  build:
    script:
      file: build.sh
      secrets:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN

      env:
        CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER", default="sccache") }}
        CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER", default="sccache") }}
        CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER", default="sccache") }}
        CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR", default="Ninja") }}
        PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL", default="4") }}
        SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET", default="") }}
        SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT", default="") }}
        SCCACHE_REGION: ${{ env.get("SCCACHE_REGION", default="") }}
        SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL", default="") }}
        SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS", default="") }}
        SCCACHE_S3_KEY_PREFIX: librmm-${{ env.get("RAPIDS_CONDA_ARCH", default="") }}

outputs:
  - package:
      name: librmm
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      script: install_librmm.sh
    requirements:
      host:
        - cmake ${{ cmake_version }}
        - cuda-version =${{ cuda_version }}
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - if: cuda_major == "11"
          then: cudatoolkit
        - rapids-logger =0.1
      run_exports:
        - ${{ pin_subpackage("librmm", upper_bound="x.x") }}
      ignore_run_exports:
        from_package:
          - ${{ compiler("cuda") }}
    tests:
      - script:
          - "test -d \"${PREFIX}/include/rmm\""
    about:
      homepage: ${{ load_from_file("python/librmm/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/librmm/pyproject.toml").project.license.text | replace(" ", "-") }}
      summary: ${{ load_from_file("python/librmm/pyproject.toml").project.description }}
  - package:
      name: librmm-tests
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      script: install_librmm_tests.sh
    requirements:
      host:
        - cmake ${{ cmake_version }}
        - cuda-version =${{ cuda_version }}
        - if: cuda_major == "11"
          then: cudatoolkit
          else: cuda-cudart-dev
      run:
        - if: cuda_major == "11"
          then: cudatoolkit
          else: cuda-cudart
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - ${{ pin_subpackage("librmm", exact=True) }}
      ignore_run_exports:
        from_package:
          - ${{ compiler("cuda") }}
          - if: cuda_major == "11"
            then: cuda-cudart-dev
    about:
      homepage: ${{ load_from_file("python/librmm/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/librmm/pyproject.toml").project.license.text | replace(" ", "-") }}
      summary: librmm test & benchmark executables
