# Copyright (c) 2018-2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

recipe:
  name: librmm-split

cache:
  source:
    path: ../../..

  build:
    script:
      content: |
        # Remove `-fdebug-prefix-map` line from CFLAGS and CXXFLAGS so the
        # incrementing version number in the compile line doesn't break the
        # cache
        set -x
        export CFLAGS=$(echo $CFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        export CXXFLAGS=$(echo $CXXFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        set +x

        ./build.sh -n -v clean librmm tests benchmarks
      secrets:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
      env:
        CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
        CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
        CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
        CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
        PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL") }}
        SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
        SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
        SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
        SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
        SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
        SCCACHE_S3_KEY_PREFIX: librmm-${{ env.get("RAPIDS_CONDA_ARCH") }}

  requirements:
    build:
      - cmake ${{ cmake_version }}
      - ninja
      - ${{ compiler("c") }}
      - ${{ compiler("cxx") }}
      - ${{ compiler("cuda") }}
      - cuda-version =${{ cuda_version }}
      - ${{ stdlib("c") }}
    host:
      - rapids-logger =0.1
      - cuda-driver-dev

outputs:
  - package:
      name: librmm
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      script:
        - cmake --install cpp/build
      dynamic_linking:
        overlinking_behavior: "error"
      prefix_detection:
        ignore:
          # See https://github.com/rapidsai/build-planning/issues/160
          - lib/librmm.so
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - cuda-version =${{ cuda_version }}
        - cuda-cudart-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - cuda-cudart
        - rapids-logger =0.1
      run_exports:
        - ${{ pin_subpackage("librmm", upper_bound="x.x") }}
      ignore_run_exports:
        from_package:
          - cuda-cudart-dev
        by_name:
          - cuda-version
    tests:
      - script:
          - "test -d \"${PREFIX}/include/rmm\""
    about:
      homepage: ${{ load_from_file("python/librmm/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/librmm/pyproject.toml").project.license.text }}
      summary: ${{ load_from_file("python/librmm/pyproject.toml").project.description }}

  - package:
      name: librmm-tests
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      script: cmake --install cpp/build --component testing
      dynamic_linking:
        overlinking_behavior: "error"
        missing_dso_allowlist:
          - "libcuda.so.1"
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}  # this is here to help with overlinking errors against libm.so.6 and friends
      host:
        - ${{ pin_subpackage("librmm", exact=True) }}
        - cuda-driver-dev
        - cuda-version =${{ cuda_version }}
        - cuda-cudart-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - ${{ pin_subpackage("librmm", exact=True) }}
        - rapids-logger =0.1
        - cuda-cudart
      ignore_run_exports:
        from_package:
          - cuda-cudart-dev
        by_name:
          - cuda-version
    about:
      homepage: ${{ load_from_file("python/librmm/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/librmm/pyproject.toml").project.license.text | replace(" ", "-") }}
      summary: librmm test & benchmark executables

  - package:
      name: librmm-example
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      script:
        content: |
          ./cpp/examples/build.sh --install
        env:
          CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
          CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
          CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
          CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
          PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL") }}
          SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
          SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
          SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
          SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
          SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
          SCCACHE_S3_KEY_PREFIX: librmm-${{ env.get("RAPIDS_CONDA_ARCH") }}
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ninja
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ compiler("cuda") }}
        - cuda-version =${{ cuda_version }}
      host:
        - cuda-version =${{ cuda_version }}
        - cuda-cudart-dev
        - ${{ pin_subpackage("librmm", exact=True) }}
      run:
        - cuda-cudart
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - ${{ pin_subpackage("librmm", exact=True) }}
      ignore_run_exports:
        from_package:
          - cuda-cudart-dev
        by_name:
          - cuda-version
          - librmm
    about:
      homepage: ${{ load_from_file("python/librmm/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/librmm/pyproject.toml").project.license.text | replace(" ", "-") }}
      summary: librmm example executables
