[tool.codespell]
# note: pre-commit passes explicit lists of files here, which this skip file list doesn't override -
# this is only to allow you to run codespell interactively
skip = "./pyproject.toml,./.git,./.github,./cpp/build,.*egg-info.*,./.mypy_cache,./benchmarks/utilities/cxxopts.hpp"
# ignore short words, and typename parameters like OffsetT
ignore-regex = "\\b(.{1,4}|[A-Z]\\w*T)\\b"
ignore-words-list = "inout"
builtin = "clear"
quiet-level = 3

[tool.ruff]
select = ["E", "F", "W"]
ignore = [
    # whitespace before :
    "E203",
]
fixable = ["ALL"]
exclude = [
    # TODO: Remove this in a follow-up where we fix __all__.
    "__init__.py",
]
line-length = 79
