# Copyright (c) 2019-2021, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set py_version=environ.get('CONDA_PY', 35) %}
{% set cuda_version='.'.join(environ.get('CUDA', '10.1').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}

package:
  name: rmm
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}_{{ cudaMallocAsync }}
  script_env:
    - RMM_BUILD_NO_GPU_TEST
    - VERSION_SUFFIX
    - CC
    - CXX
    - CUDAHOSTCXX

requirements:
  host:
    - python
    - librmm {{ version }}
    - setuptools
    - cython >=0.29,<0.30
    - spdlog>=1.8.5,<2.0.0a0
    - cudatoolkit {{ cuda_version }}.*
  run:
    - python
    - numba >=0.49
    - numpy
{% if cudaMallocAsync == "has_cma" %}
    - {{ pin_compatible('cudatoolkit', max_pin='x', lower_bound='11.2') }} # cudatoolkit >=11.2,<12.0.0
{% else %}
    - {{ pin_compatible('cudatoolkit', upper_bound='11.2', lower_bound='11.0') }} # cudatoolkit >=11.0,<11.2
{% endif %}

test:
  imports:
    - rmm

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: rmm library
