# Copyright (c) 2020, NVIDIA CORPORATION.
from rmm._lib.memory_resource import (
    BinningMemoryResource,
    CudaMemoryResource,
    FixedSizeMemoryResource,
    LoggingResourceAdaptor,
    ManagedMemoryResource,
    MemoryResource,
    PoolMemoryResource,
    _flush_logs,
    _initialize,
    _set_per_device_resource as set_per_device_resource,
    get_per_device_resource,
    set_current_device_resource,
    get_current_device_resource,
    get_per_device_resource_type,
    get_current_device_resource_type,
    is_initialized,
)

__all__ = [
    "BinningMemoryResource",
    "CudaMemoryResource",
    "FixedSizeMemoryResource",
    "LoggingResourceAdaptor",
    "ManagedMemoryResource",
    "MemoryResource",
    "PoolMemoryResource",
    "_flush_logs",
    "_initialize",
    "set_per_device_resource",
    "get_per_device_resource",
    "set_current_device_resource",
    "get_current_device_resource",
    "get_per_device_resource_type",
    "get_current_device_resource_type",
    "is_initialized",
]
