# SPDX-FileCopyrightText: Copyright (c) 2020-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

from enum import IntEnum
from typing import Any, Optional

class CudaStreamFlags(IntEnum):
    SYNC_DEFAULT = ...
    NON_BLOCKING = ...

class _OwningStream:
    def __init__(self, flags: CudaStreamFlags = ...) -> None: ...

class Stream:
    def __init__(
        self, obj: Optional[Any] = None, flags: CudaStreamFlags = ...
    ) -> None: ...
    def __cuda_stream__(self) -> tuple[int, int]: ...
    def synchronize(self) -> None: ...
    def is_default(self) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...

DEFAULT_STREAM: Stream
LEGACY_DEFAULT_STREAM: Stream
PER_THREAD_DEFAULT_STREAM: Stream
