name: conda-env-files

on:
  pull_request:

jobs:
  check_generated_files:
    name: ensure conda env files are up-to-date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install rapids-env-generator
        run: pip install git+https://github.com/rapidsai/rapids-env-generator.git@initial-commit#egg=rapids-env-generator
      - name: Run rapids-env-generator
        run: |
          find conda/environments -type f ! -name envs.yaml -delete # delete existing environment files
          reg
      - name: Ensure generated environment files are up-to-date
        run: |
          git diff --exit-code
          test -z "$(git status --porcelain conda/environments)" # ensures there are no untracked environment files
      - name: Ensure a "full" environment exists
        run: |
          # ensure .envs.full exists
          yq -e '.envs | has("full")' < conda/environments/envs.yaml

          # ensure .envs.full.includes has all dependency lists
          export RESERVED_KEYS='["envs", "specifics", "channels"]'
          export DEP_LISTS=$(
            yq -e -o json \
            'keys |
            . - (strenv(RESERVED_KEYS) | from_json) |
            sort' < conda/environments/envs.yaml
          )
          export FULL_ENV_INCLUDES=$(
            yq -e -o json \
            '.envs.full.includes |
            sort' < conda/environments/envs.yaml
          )
          yq -ne 'strenv(FULL_ENV_INCLUDES) == strenv(DEP_LISTS)'
