name: Auto Assign New Issues to Triage Project

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to New Issues to Triage Project
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: Process bug issues
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: contains(github.event.issue.labels.*.name, 'bug') && contains(github.event.issue.labels.*.name, '? - Needs Triage')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/rapidsai/rmm/projects/12
        GITHUB_PROJECT_COLUMN_NAME: 'Needs prioritizing'
    - name: Process feature issues
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: contains(github.event.issue.labels.*.name, 'feature request') && contains(github.event.issue.labels.*.name, '? - Needs Triage')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/rapidsai/rmm/projects/13
        GITHUB_PROJECT_COLUMN_NAME: 'Needs prioritizing'
    - name: Process other issues
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: contains(github.event.issue.labels.*.name, '? - Needs Triage') && (!contains(github.event.issue.labels.*.name, 'bug') && !contains(github.event.issue.labels.*.name, 'feature request'))
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/rapidsai/rmm/projects/14
        GITHUB_PROJECT_COLUMN_NAME: 'Needs prioritizing'
